### Competition EDA

In [53]:
import re
import pandas as pd
import statistics
from tqdm import tqdm

tqdm.pandas()

In [54]:
import sys
sys.path.append("..")

from src.solvers.bit_manipulation import BitManipulationSolver
from src.solvers.equations import EnsembleEquationsSolver
from src.solvers.encryption import EncryptionSolver
from src.solvers.unit_conversion import UnitConversionSolver
from src.solvers.gravitational import GravitationalSolver
from src.solvers.numeral_system import NumeralSystemSolver

In [55]:
data = pd.read_csv("../data/raw/train.csv")

In [56]:
data

,id,prompt,answer
0,00066667,"In Alice's Wonderland, a secret bit manipulati...",10010111
1,000b53cf,"In Alice's Wonderland, a secret bit manipulati...",01000011
2,00189f6a,"In Alice's Wonderland, secret encryption rules...",cat imagines book
3,001b24c4,"In Alice's Wonderland, numbers are secretly co...",XXXVIII
4,001c63cb,"In Alice's Wonderland, secret encryption rules...",wizard creates secret
...,...,...,...
9495,ffce9e31,"In Alice's Wonderland, a secret bit manipulati...",01100110
9496,ffd5bada,"In Alice's Wonderland, a secret unit conversio...",32.45
9497,ffd89354,"In Alice's Wonderland, secret encryption rules...",student sees the curious mirror
9498,ffdfb678,"In Alice's Wonderland, secret encryption rules...",the curious mouse creates
9499,ffe680c2,"In Alice's Wonderland, the gravitational const...",57.0

In [57]:
data["prompt_eda"] = data.prompt.str.split('.').apply(lambda x: x[0])

In [58]:
print(data.prompt_eda.unique())

<ArrowStringArray>
['In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers',
                       'In Alice's Wonderland, secret encryption rules are used on text',
 'In Alice's Wonderland, numbers are secretly converted into a different numeral system',
            'In Alice's Wonderland, a secret unit conversion is applied to measurements',
           'In Alice's Wonderland, the gravitational constant has been secretly changed',
   'In Alice's Wonderland, a secret set of transformation rules is applied to equations']
Length: 6, dtype: str

In [59]:
task_classes = {
    "In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers":  "bit manipulation",
    "In Alice's Wonderland, secret encryption rules are used on text": "encryption",
    "In Alice's Wonderland, numbers are secretly converted into a different numeral system": "conversion to diff numeral system",
    "In Alice's Wonderland, a secret unit conversion is applied to measurements": "unit conversion",
    "In Alice's Wonderland, the gravitational constant has been secretly changed": "gravitational",
    "In Alice's Wonderland, a secret set of transformation rules is applied to equations": "equations transformation"
}

In [60]:
data["label"] = data.prompt_eda.map(task_classes)
data["label"].value_counts()

label
bit manipulation                     1602
gravitational                        1597
unit conversion                      1594
encryption                           1576
conversion to diff numeral system    1576
equations transformation             1555
Name: count, dtype: int64

In [61]:
### Just check data

In [62]:
data.iloc[2].prompt

"In Alice's Wonderland, secret encryption rules are used on text. Here are some examples:\nucoov pwgtfyoqg vorq yrjjoe -> queen discovers near valley\npqrsfv pqorzg wvgwpo trgbjo -> dragon dreams inside castle\ngbcpovb tqorbog bxo zrswtrj pffq -> student creates the magical door\nbxo sfjpov pqrsfv dfjjfig -> the golden dragon follows\nnqwvtogg qorpg bxo zegboqwfcg gotqob -> princess reads the mysterious secret\nNow, decrypt the following text: trb wzrswvog hffk"

In [63]:
data[data.label == "equations transformation"].sample(1).prompt.to_list()

["In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n88+71 = 501\n76$06 = 9104\n99+56 = 461\n86+56 = 331\n93$23 = 7421\nNow, determine the result for: 88$13"]

In [64]:
data[data.label == "bit manipulation"].sample(1).prompt.to_list()

["In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n11101111 -> 00011011\n01111010 -> 00010100\n01011110 -> 00010100\n10111110 -> 00101101\n11101010 -> 00010000\n01110001 -> 00000000\n00000010 -> 00000000\n11100011 -> 00000000\n11101100 -> 00011001\n11011001 -> 00110010\n\nNow, determine the output for: 11000101"]

In [65]:
data["label_format"] = data.prompt.str.split("\n").apply(lambda x: x[-1])

In [66]:
data.groupby("label")["label_format"].value_counts().to_dict()

{('bit manipulation', 'Now, determine the output for: 01010101'): 13,
 ('bit manipulation', 'Now, determine the output for: 11110101'): 13,
 ('bit manipulation', 'Now, determine the output for: 11001101'): 12,
 ('bit manipulation', 'Now, determine the output for: 10000001'): 12,
 ('bit manipulation', 'Now, determine the output for: 11001000'): 12,
 ('bit manipulation', 'Now, determine the output for: 10101001'): 12,
 ('bit manipulation', 'Now, determine the output for: 10001001'): 12,
 ('bit manipulation', 'Now, determine the output for: 01111110'): 11,
 ('bit manipulation', 'Now, determine the output for: 11101101'): 11,
 ('bit manipulation', 'Now, determine the output for: 11111010'): 11,
 ('bit manipulation', 'Now, determine the output for: 11100110'): 11,
 ('bit manipulation', 'Now, determine the output for: 11000110'): 11,
 ('bit manipulation', 'Now, determine the output for: 00100110'): 11,
 ('bit manipulation', 'Now, determine the output for: 00110000'): 10,
 ('bit manipulation', 'Now, determine the output for: 11110010'): 10,
 ('bit manipulation', 'Now, determine the output for: 01100011'): 10,
 ('bit manipulation', 'Now, determine the output for: 10001100'): 10,
 ('bit manipulation', 'Now, determine the output for: 00001100'): 10,
 ('bit manipulation', 'Now, determine the output for: 00101011'): 10,
 ('bit manipulation', 'Now, determine the output for: 10110010'): 10,
 ('bit manipulation', 'Now, determine the output for: 00011100'): 10,
 ('bit manipulation', 'Now, determine the output for: 10001111'): 10,
 ('bit manipulation', 'Now, determine the output for: 01011011'): 10,
 ('bit manipulation', 'Now, determine the output for: 00110011'): 10,
 ('bit manipulation', 'Now, determine the output for: 01100000'): 10,
 ('bit manipulation', 'Now, determine the output for: 11001010'): 10,
 ('bit manipulation', 'Now, determine the output for: 10011010'): 10,
 ('bit manipulation', 'Now, determine the output for: 10100110'): 10,
 ('bit manipulation', 'Now, determine the output for: 00010110'): 9,
 ('bit manipulation', 'Now, determine the output for: 11000101'): 9,
 ('bit manipulation', 'Now, determine the output for: 10011111'): 9,
 ('bit manipulation', 'Now, determine the output for: 01000111'): 9,
 ('bit manipulation', 'Now, determine the output for: 01100100'): 9,
 ('bit manipulation', 'Now, determine the output for: 01101001'): 9,
 ('bit manipulation', 'Now, determine the output for: 11110000'): 9,
 ('bit manipulation', 'Now, determine the output for: 01101111'): 9,
 ('bit manipulation', 'Now, determine the output for: 01100111'): 9,
 ('bit manipulation', 'Now, determine the output for: 10010111'): 9,
 ('bit manipulation', 'Now, determine the output for: 00010011'): 9,
 ('bit manipulation', 'Now, determine the output for: 10100001'): 9,
 ('bit manipulation', 'Now, determine the output for: 01011101'): 9,
 ('bit manipulation', 'Now, determine the output for: 01111100'): 9,
 ('bit manipulation', 'Now, determine the output for: 01100101'): 9,
 ('bit manipulation', 'Now, determine the output for: 00001010'): 9,
 ('bit manipulation', 'Now, determine the output for: 11011011'): 9,
 ('bit manipulation', 'Now, determine the output for: 00010010'): 9,
 ('bit manipulation', 'Now, determine the output for: 00100010'): 9,
 ('bit manipulation', 'Now, determine the output for: 11111001'): 9,
 ('bit manipulation', 'Now, determine the output for: 10101101'): 8,
 ('bit manipulation', 'Now, determine the output for: 11010100'): 8,
 ('bit manipulation', 'Now, determine the output for: 11011001'): 8,
 ('bit manipulation', 'Now, determine the output for: 00010000'): 8,
 ('bit manipulation', 'Now, determine the output for: 11010001'): 8,
 ('bit manipulation', 'Now, determine the output for: 00010101'): 8,
 ('bit manipulation', 'Now, determine the output for: 11101010'): 8,
 ('bit manipulation', 'Now, determine the output for: 00011110'): 8,
 ('bit manipulation', 'Now, determine the output for: 11011100'): 8,
 ('bit manipulation', 'Now, determine the output for: 10010000'): 8,
 ('bit manipulation', 'Now, determine the output for: 11000111'): 8,
 ('bit manipulation', 'Now, determine the output for: 01001101'): 8,
 ('bit manipulation', 'Now, determine the output for: 00111000'): 8,
 ('bit manipulation', 'Now, determine the output for: 11111110'): 8,
 ('bit manipulation', 'Now, determine the output for: 00111001'): 8,
 ('bit manipulation', 'Now, determine the output for: 01011010'): 8,
 ('bit manipulation', 'Now, determine the output for: 01001100'): 8,
 ('bit manipulation', 'Now, determine the output for: 11110100'): 8,
 ('bit manipulation', 'Now, determine the output for: 01110100'): 8,
 ('bit manipulation', 'Now, determine the output for: 10010011'): 8,
 ('bit manipulation', 'Now, determine the output for: 10011100'): 8,
 ('bit manipulation', 'Now, determine the output for: 11111101'): 8,
 ('bit manipulation', 'Now, determine the output for: 00100001'): 8,
 ('bit manipulation', 'Now, determine the output for: 00000010'): 8,
 ('bit manipulation', 'Now, determine the output for: 11001001'): 8,
 ('bit manipulation', 'Now, determine the output for: 11011000'): 8,
 ('bit manipulation', 'Now, determine the output for: 11001110'): 8,
 ('bit manipulation', 'Now, determine the output for: 11111011'): 8,
 ('bit manipulation', 'Now, determine the output for: 10110101'): 8,
 ('bit manipulation', 'Now, determine the output for: 10110100'): 8,
 ('bit manipulation', 'Now, determine the output for: 00010100'): 8,
 ('bit manipulation', 'Now, determine the output for: 11100001'): 8,
 ('bit manipulation', 'Now, determine the output for: 11011101'): 8,
 ('bit manipulation', 'Now, determine the output for: 11000010'): 8,
 ('bit manipulation', 'Now, determine the output for: 01001000'): 8,
 ('bit manipulation', 'Now, determine the output for: 10011101'): 8,
 ('bit manipulation', 'Now, determine the output for: 01011001'): 7,
 ('bit manipulation', 'Now, determine the output for: 10111110'): 7,
 ('bit manipulation', 'Now, determine the output for: 10000100'): 7,
 ('bit manipulation', 'Now, determine the output for: 10110001'): 7,
 ('bit manipulation', 'Now, determine the output for: 00100100'): 7,
 ('bit manipulation', 'Now, determine the output for: 01110011'): 7,
 ('bit manipulation', 'Now, determine the output for: 10000011'): 7,
 ('bit manipulation', 'Now, determine the output for: 01011000'): 7,
 ('bit manipulation', 'Now, determine the output for: 10010100'): 7,
 ('bit manipulation', 'Now, determine the output for: 11101000'): 7,
 ('bit manipulation', 'Now, determine the output for: 10001110'): 7,
 ('bit manipulation', 'Now, determine the output for: 00101111'): 7,
 ('bit manipulation', 'Now, determine the output for: 10010110'): 7,
 ('bit manipulation', 'Now, determine the output for: 00100101'): 7,
 ('bit manipulation', 'Now, determine the output for: 01110001'): 7,
 ('bit manipulation', 'Now, determine the output for: 00111101'): 7,
 ('bit manipulation', 'Now, determine the output for: 00100000'): 7,
 ('bit manipulation', 'Now, determine the output for: 10000110'): 7,
 ('bit manipulation', 'Now, determine the output for: 01111111'): 7,
 ('bit manipulation', 'Now, determine the output for: 01010011'): 7,
 ('bit manipulation', 'Now, determine the output for: 01001110'): 7,
 ('bit manipulation', 'Now, determine the output for: 00111010'): 7,
 ('bit manipulation', 'Now, determine the output for: 01010010'): 7,
 ('bit manipulation', 'Now, determine the output for: 10100000'): 7,
 ('bit manipulation', 'Now, determine the output for: 01010000'): 7,
 ('bit manipulation', 'Now, determine the output for: 11000100'): 7,
 ('bit manipulation', 'Now, determine the output for: 01001010'): 7,
 ('bit manipulation', 'Now, determine the output for: 11010010'): 7,
 ('bit manipulation', 'Now, determine the output for: 11110001'): 7,
 ('bit manipulation', 'Now, determine the output for: 10101100'): 7,
 ('bit manipulation', 'Now, determine the output for: 10000010'): 7,
 ('bit manipulation', 'Now, determine the output for: 00101110'): 7,
 ('bit manipulation', 'Now, determine the output for: 00110100'): 6,
 ('bit manipulation', 'Now, determine the output for: 11100000'): 6,
 ('bit manipulation', 'Now, determine the output for: 01100110'): 6,
 ('bit manipulation', 'Now, determine the output for: 01101010'): 6,
 ('bit manipulation', 'Now, determine the output for: 11001011'): 6,
 ('bit manipulation', 'Now, determine the output for: 11110111'): 6,
 ('bit manipulation', 'Now, determine the output for: 10011011'): 6,
 ('bit manipulation', 'Now, determine the output for: 10010010'): 6,
 ('bit manipulation', 'Now, determine the output for: 11110011'): 6,
 ('bit manipulation', 'Now, determine the output for: 00001110'): 6,
 ('bit manipulation', 'Now, determine the output for: 11101011'): 6,
 ('bit manipulation', 'Now, determine the output for: 10111010'): 6,
 ('bit manipulation', 'Now, determine the output for: 01000101'): 6,
 ('bit manipulation', 'Now, determine the output for: 00000101'): 6,
 ('bit manipulation', 'Now, determine the output for: 10100100'): 6,
 ('bit manipulation', 'Now, determine the output for: 01000001'): 6,
 ('bit manipulation', 'Now, determine the output for: 11011110'): 6,
 ('bit manipulation', 'Now, determine the output for: 00110101'): 6,
 ('bit manipulation', 'Now, determine the output for: 10101011'): 6,
 ('bit manipulation', 'Now, determine the output for: 10111011'): 6,
 ('bit manipulation', 'Now, determine the output for: 10011001'): 6,
 ('bit manipulation', 'Now, determine the output for: 10010101'): 6,
 ('bit manipulation', 'Now, determine the output for: 11101111'): 6,
 ('bit manipulation', 'Now, determine the output for: 00101100'): 6,
 ('bit manipulation', 'Now, determine the output for: 00110111'): 6,
 ('bit manipulation', 'Now, determine the output for: 01000000'): 6,
 ('bit manipulation', 'Now, determine the output for: 00000110'): 6,
 ('bit manipulation', 'Now, determine the output for: 01000100'): 6,
 ('bit manipulation', 'Now, determine the output for: 10100111'): 6,
 ('bit manipulation', 'Now, determine the output for: 11000000'): 6,
 ('bit manipulation', 'Now, determine the output for: 01111001'): 6,
 ('bit manipulation', 'Now, determine the output for: 11100111'): 6,
 ('bit manipulation', 'Now, determine the output for: 00000111'): 6,
 ('bit manipulation', 'Now, determine the output for: 00101000'): 6,
 ('bit manipulation', 'Now, determine the output for: 01110110'): 6,
 ('bit manipulation', 'Now, determine the output for: 01110101'): 6,
 ('bit manipulation', 'Now, determine the output for: 01101101'): 6,
 ('bit manipulation', 'Now, determine the output for: 00000011'): 6,
 ('bit manipulation', 'Now, determine the output for: 00110001'): 6,
 ('bit manipulation', 'Now, determine the output for: 00000000'): 6,
 ('bit manipulation', 'Now, determine the output for: 10101110'): 6,
 ('bit manipulation', 'Now, determine the output for: 11010000'): 5,
 ('bit manipulation', 'Now, determine the output for: 00001101'): 5,
 ('bit manipulation', 'Now, determine the output for: 00000001'): 5,
 ('bit manipulation', 'Now, determine the output for: 10001101'): 5,
 ('bit manipulation', 'Now, determine the output for: 10110111'): 5,
 ('bit manipulation', 'Now, determine the output for: 10000111'): 5,
 ('bit manipulation', 'Now, determine the output for: 10111001'): 5,
 ('bit manipulation', 'Now, determine the output for: 10011000'): 5,
 ('bit manipulation', 'Now, determine the output for: 01101110'): 5,
 ('bit manipulation', 'Now, determine the output for: 01011111'): 5,
 ('bit manipulation', 'Now, determine the output for: 11101100'): 5,
 ('bit manipulation', 'Now, determine the output for: 01000010'): 5,
 ('bit manipulation', 'Now, determine the output for: 01110000'): 5,
 ('bit manipulation', 'Now, determine the output for: 00011001'): 5,
 ('bit manipulation', 'Now, determine the output for: 10001000'): 5,
 ('bit manipulation', 'Now, determine the output for: 01100001'): 5,
 ('bit manipulation', 'Now, determine the output for: 00010111'): 5,
 ('bit manipulation', 'Now, determine the output for: 01001001'): 5,
 ('bit manipulation', 'Now, determine the output for: 10000101'): 5,
 ('bit manipulation', 'Now, determine the output for: 01110111'): 5,
 ('bit manipulation', 'Now, determine the output for: 11010110'): 5,
 ('bit manipulation', 'Now, determine the output for: 01101011'): 5,
 ('bit manipulation', 'Now, determine the output for: 11100011'): 5,
 ('bit manipulation', 'Now, determine the output for: 11111000'): 5,
 ('bit manipulation', 'Now, determine the output for: 00111100'): 5,
 ('bit manipulation', 'Now, determine the output for: 11100101'): 4,
 ('bit manipulation', 'Now, determine the output for: 00100111'): 4,
 ('bit manipulation', 'Now, determine the output for: 01001111'): 4,
 ('bit manipulation', 'Now, determine the output for: 01111010'): 4,
 ('bit manipulation', 'Now, determine the output for: 00111111'): 4,
 ('bit manipulation', 'Now, determine the output for: 10111100'): 4,
 ('bit manipulation', 'Now, determine the output for: 11101001'): 4,
 ('bit manipulation', 'Now, determine the output for: 11011111'): 4,
 ('bit manipulation', 'Now, determine the output for: 00100011'): 4,
 ('bit manipulation', 'Now, determine the output for: 01100010'): 4,
 ('bit manipulation', 'Now, determine the output for: 10001011'): 4,
 ('bit manipulation', 'Now, determine the output for: 00011101'): 4,
 ('bit manipulation', 'Now, determine the output for: 01010001'): 4,
 ('bit manipulation', 'Now, determine the output for: 01011110'): 4,
 ('bit manipulation', 'Now, determine the output for: 11011010'): 4,
 ('bit manipulation', 'Now, determine the output for: 01010111'): 4,
 ('bit manipulation', 'Now, determine the output for: 11111100'): 4,
 ('bit manipulation', 'Now, determine the output for: 11000001'): 4,
 ('bit manipulation', 'Now, determine the output for: 00101101'): 4,
 ('bit manipulation', 'Now, determine the output for: 01010100'): 4,
 ('bit manipulation', 'Now, determine the output for: 10011110'): 4,
 ('bit manipulation', 'Now, determine the output for: 11000011'): 4,
 ('bit manipulation', 'Now, determine the output for: 10001010'): 4,
 ('bit manipulation', 'Now, determine the output for: 11001100'): 4,
 ('bit manipulation', 'Now, determine the output for: 11111111'): 4,
 ('bit manipulation', 'Now, determine the output for: 10111111'): 4,
 ('bit manipulation', 'Now, determine the output for: 01101000'): 4,
 ('bit manipulation', 'Now, determine the output for: 00001001'): 4,
 ('bit manipulation', 'Now, determine the output for: 01000110'): 4,
 ('bit manipulation', 'Now, determine the output for: 10110011'): 4,
 ('bit manipulation', 'Now, determine the output for: 10000000'): 4,
 ('bit manipulation', 'Now, determine the output for: 00110110'): 4,
 ('bit manipulation', 'Now, determine the output for: 00011010'): 4,
 ('bit manipulation', 'Now, determine the output for: 10101111'): 3,
 ('bit manipulation', 'Now, determine the output for: 00101001'): 3,
 ('bit manipulation', 'Now, determine the output for: 10111101'): 3,
 ('bit manipulation', 'Now, determine the output for: 00111110'): 3,
 ('bit manipulation', 'Now, determine the output for: 11100010'): 3,
 ('bit manipulation', 'Now, determine the output for: 11101110'): 3,
 ('bit manipulation', 'Now, determine the output for: 10101000'): 3,
 ('bit manipulation', 'Now, determine the output for: 10111000'): 3,
 ('bit manipulation', 'Now, determine the output for: 00001011'): 3,
 ('bit manipulation', 'Now, determine the output for: 01110010'): 3,
 ('bit manipulation', 'Now, determine the output for: 01000011'): 3,
 ('bit manipulation', 'Now, determine the output for: 00110010'): 3,
 ('bit manipulation', 'Now, determine the output for: 00010001'): 3,
 ('bit manipulation', 'Now, determine the output for: 00001000'): 3,
 ('bit manipulation', 'Now, determine the output for: 11110110'): 3,
 ('bit manipulation', 'Now, determine the output for: 00011000'): 3,
 ('bit manipulation', 'Now, determine the output for: 00111011'): 3,
 ('bit manipulation', 'Now, determine the output for: 11001111'): 3,
 ('bit manipulation', 'Now, determine the output for: 11100100'): 3,
 ('bit manipulation', 'Now, determine the output for: 01001011'): 3,
 ('bit manipulation', 'Now, determine the output for: 11010111'): 3,
 ('bit manipulation', 'Now, determine the output for: 01111011'): 3,
 ('bit manipulation', 'Now, determine the output for: 01101100'): 3,
 ('bit manipulation', 'Now, determine the output for: 01111101'): 3,
 ('bit manipulation', 'Now, determine the output for: 01011100'): 3,
 ('bit manipulation', 'Now, determine the output for: 11010101'): 3,
 ('bit manipulation', 'Now, determine the output for: 10100010'): 3,
 ('bit manipulation', 'Now, determine the output for: 10101010'): 3,
 ('bit manipulation', 'Now, determine the output for: 10100101'): 3,
 ('bit manipulation', 'Now, determine the output for: 10100011'): 2,
 ('bit manipulation', 'Now, determine the output for: 00101010'): 2,
 ('bit manipulation', 'Now, determine the output for: 00011011'): 2,
 ('bit manipulation', 'Now, determine the output for: 10110110'): 2,
 ('bit manipulation', 'Now, determine the output for: 00001111'): 2,
 ('bit manipulation', 'Now, determine the output for: 00000100'): 2,
 ('bit manipulation', 'Now, determine the output for: 01111000'): 1,
 ('bit manipulation', 'Now, determine the output for: 01010110'): 1,
 ('bit manipulation', 'Now, determine the output for: 11010011'): 1,
 ('bit manipulation', 'Now, determine the output for: 10110000'): 1,
 ('bit manipulation', 'Now, determine the output for: 10010001'): 1,
 ('bit manipulation', 'Now, determine the output for: 00011111'): 1,
 ('conversion to diff numeral system',
  'Now, write the number 73 in the Wonderland numeral system.'): 25,
 ('conversion to diff numeral system',
  'Now, write the number 52 in the Wonderland numeral system.'): 24,
 ('conversion to diff numeral system',
  'Now, write the number 6 in the Wonderland numeral system.'): 24,
 ('conversion to diff numeral system',
  'Now, write the number 49 in the Wonderland numeral system.'): 24,
 ('conversion to diff numeral system',
  'Now, write the number 17 in the Wonderland numeral system.'): 24,
 ('conversion to diff numeral system',
  'Now, write the number 13 in the Wonderland numeral system.'): 23,
 ('conversion to diff numeral system',
  'Now, write the number 21 in the Wonderland numeral system.'): 22,
 ('conversion to diff numeral system',
  'Now, write the number 14 in the Wonderland numeral system.'): 22,
 ('conversion to diff numeral system',
  'Now, write the number 19 in the Wonderland numeral system.'): 22,
 ('conversion to diff numeral system',
  'Now, write the number 51 in the Wonderland numeral system.'): 21,
 ('conversion to diff numeral system',
  'Now, write the number 99 in the Wonderland numeral system.'): 21,
 ('conversion to diff numeral system',
  'Now, write the number 35 in the Wonderland numeral system.'): 21,
 ('conversion to diff numeral system',
  'Now, write the number 38 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 66 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 32 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 83 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 2 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 36 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 79 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 34 in the Wonderland numeral system.'): 20,
 ('conversion to diff numeral system',
  'Now, write the number 86 in the Wonderland numeral system.'): 19,
 ('conversion to diff numeral system',

In [67]:
def extract_template(text):
    if not isinstance(text, str):
        return str(text)
        
    text = text.strip()
    
    # "Now, determine the output for: <TARGET>"
    if ':' in text:
        return re.sub(r':\s*.*$', ': <TARGET>', text)
        
    # "If <NUM> @ <NUM> = <NUM>, what is X?"
    text = re.sub(r'\b\d+\b', '<NUM>', text)
    
    return text

data["pattern"] = data["label_format"].apply(extract_template)

patterns_summary = data.groupby("label")["pattern"].value_counts().to_frame("count").reset_index()

for label in patterns_summary['label'].unique():
    print(f"\n=== {label} ===")
    subset = patterns_summary[patterns_summary['label'] == label]
    for _, row in subset.iterrows():
        print(f"{row['count']:>4} | {row['pattern']}")

=== bit manipulation ===
1602 | Now, determine the output for: <TARGET>

=== conversion to diff numeral system ===
1576 | Now, write the number <NUM> in the Wonderland numeral system.

=== encryption ===
1576 | Now, decrypt the following text: <TARGET>

=== equations transformation ===
1555 | Now, determine the result for: <TARGET>

=== gravitational ===
  25 | Now, determine the falling distance for t = <NUM>.32s given d = <NUM>.<NUM>*g*t^<NUM>.
  24 | Now, determine the falling distance for t = <NUM>.82s given d = <NUM>.<NUM>*g*t^<NUM>.
  24 | Now, determine the falling distance for t = <NUM>.72s given d = <NUM>.<NUM>*g*t^<NUM>.
  23 | Now, determine the falling distance for t = <NUM>.79s given d = <NUM>.<NUM>*g*t^<NUM>.
  23 | Now, determine the falling distance for t = <NUM>.87s given d = <NUM>.<NUM>*g*t^<NUM>.
  22 | Now, determine the falling distance for t = <NUM>.45s given d = <NUM>.<NUM>*g*t^<NUM>.
  22 | Now, determine the falling distance for t = <NUM>.57s given d = <NUM>.<NUM>*g*t^<NUM>.
  22 | Now, determine the falling distance for t = <NUM>.78s given d = <NUM>.<NUM>*g*t^<NUM>.
  21 | Now, determine the falling distance for t = <NUM>.17s given d = <NUM>.<NUM>*g*t^<NUM>.
  21 | Now, determine the falling distance for t = <NUM>.74s given d = <NUM>.<NUM>*g*t^<NUM>.
  20 | Now, determine the falling distance for t = <NUM>.25s given d = <NUM>.<NUM>*g*t^<NUM>.
  20 | Now, determine the falling distance for t = <NUM>.05s given d = <NUM>.<NUM>*g*t^<NUM>.
  20 | Now, determine the falling distance for t = <NUM>.91s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.12s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.19s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.49s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.88s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.92s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.6s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.1s given d = <NUM>.<NUM>*g*t^<NUM>.
  19 | Now, determine the falling distance for t = <NUM>.85s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.51s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.27s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.38s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.28s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.71s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.08s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.84s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.58s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.93s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.62s given d = <NUM>.<NUM>*g*t^<NUM>.
  18 | Now, determine the falling distance for t = <NUM>.7s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.41s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.35s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.97s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.53s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.94s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.21s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.5s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.73s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.66s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.96s given d = <NUM>.<NUM>*g*t^<NUM>.
  17 | Now, determine the falling distance for t = <NUM>.64s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.65s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.2s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.13s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.68s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.81s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.56s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.04s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.99s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.37s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.48s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.55s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.77s given d = <NUM>.<NUM>*g*t^<NUM>.
  16 | Now, determine the falling distance for t = <NUM>.0s given d = <NUM>.<NUM>*g*t^<NUM>.
  15 | Now, determine the falling distance for t = <NUM>.06s given d = <NUM>.<NUM>*g*t^<NUM>.
  15 | Now, determine the falling distance for t = <NUM>.76s given d = <NUM>.<NUM>*g*t^<NUM>.
  15 | Now, determine the falling distance for t = <NUM>.03s given d = <NUM>.<NUM>*g*t^<NUM>.
  15 | Now, determine the falling distance for t = <NUM>.29s given d = <NUM>.<NUM>*g*t^<NUM>.
  15 | Now, determine the falling distance for t = <NUM>.3s given d = <NUM>.<NUM>*g*t^<NUM>.
  15 | Now, determine the falling distance for t = <NUM>.95s given d = <NUM>.<NUM>*g*t^<NUM>.
  15 | Now, determine the falling distance for t = <NUM>.63s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.01s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.46s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.31s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.02s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.89s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.11s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.42s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.8s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.9s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.16s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.22s given d = <NUM>.<NUM>*g*t^<NUM>.
  14 | Now, determine the falling distance for t = <NUM>.54s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.98s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.69s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.44s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.14s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.67s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.4s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.52s given d = <NUM>.<NUM>*g*t^<NUM>.
  13 | Now, determine the falling distance for t = <NUM>.09s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.33s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.83s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.23s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.07s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.47s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.18s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.86s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.15s given d = <NUM>.<NUM>*g*t^<NUM>.
  12 | Now, determine the falling distance for t = <NUM>.75s given d = <NUM>.<NUM>*g*t^<NUM>.
  11 | Now, determine the falling distance for t = <NUM>.36s given d = <NUM>.<NUM>*g*t^<NUM>.
  11 | Now, determine the falling distance for t = <NUM>.59s given d = <NUM>.<NUM>*g*t^<NUM>.
  11 | Now, determine the falling distance for t = <NUM>.26s given d = <NUM>.<NUM>*g*t^<NUM>.
  11 | Now, determine the falling distance for t = <NUM>.43s given d = <NUM>.<NUM>*g*t^<NUM>.
  10 | Now, determine the falling distance for t = <NUM>.24s given d = <NUM>.<NUM>*g*t^<NUM>.
  10 | Now, determine the falling distance for t = <NUM>.61s given d = <NUM>.<NUM>*g*t^<NUM>.
   9 | Now, determine the falling distance for t = <NUM>.39s given d = <NUM>.<NUM>*g*t^<NUM>.
   7 | Now, determine the falling distance for t = <NUM>.34s given d = <NUM>.<NUM>*g*t^<NUM>.

=== unit conversion ===
1594 | Now, convert the following measurement: <TARGET>

### conversion to diff numeral system

In [68]:
numeral_df = data[data['label'] == 'conversion to diff numeral system'].copy()

solver = NumeralSystemSolver()

numeral_df['generated_cot'] = numeral_df['prompt'].apply(solver.generate_cot)

numeral_df['computed_answer'] = numeral_df['generated_cot'].apply(solver.extract_answer)

numeral_df['is_correct'] = numeral_df['computed_answer'].astype(str).str.strip() == numeral_df['answer'].astype(str).str.strip()

accuracy = numeral_df['is_correct'].mean()
print(f"Accuracy by '{numeral_df['label'].iloc[0]}': {accuracy * 100:.2f}%")

Accuracy by 'conversion to diff numeral system': 100.00%

In [69]:
numeral_df

,id,prompt,answer,prompt_eda,label,label_format,pattern,generated_cot,computed_answer,is_correct
3,001b24c4,"In Alice's Wonderland, numbers are secretly co...",XXXVIII,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 38 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,XXXVIII,True
14,00600e6e,"In Alice's Wonderland, numbers are secretly co...",LXVII,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 67 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,LXVII,True
30,00d9f682,"In Alice's Wonderland, numbers are secretly co...",C,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 100 in the Wonderland nu...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,C,True
36,0106eb4a,"In Alice's Wonderland, numbers are secretly co...",LXXXIV,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 84 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,LXXXIV,True
37,0122d53a,"In Alice's Wonderland, numbers are secretly co...",LI,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 51 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,LI,True
...,...,...,...,...,...,...,...,...,...,...
9476,ff5cb472,"In Alice's Wonderland, numbers are secretly co...",V,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 5 in the Wonderland nume...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,V,True
9477,ff5f4ff2,"In Alice's Wonderland, numbers are secretly co...",LI,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 51 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,LI,True
9478,ff612478,"In Alice's Wonderland, numbers are secretly co...",XXI,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 21 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,XXI,True
9479,ff650fc3,"In Alice's Wonderland, numbers are secretly co...",XXXVI,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 36 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,XXXVI,True
9492,ffaf05c5,"In Alice's Wonderland, numbers are secretly co...",XLVIII,"In Alice's Wonderland, numbers are secretly co...",conversion to diff numeral system,"Now, write the number 48 in the Wonderland num...","Now, write the number <NUM> in the Wonderland ...",Let's identify the secret numeral system used ...,XLVIII,True

### unit conversion

In [70]:
unit_df = data[data['label'] == 'unit conversion'].copy()

solver = UnitConversionSolver()

unit_df['generated_cot'] = unit_df['prompt'].apply(solver.generate_cot)

unit_df['computed_answer'] = unit_df['generated_cot'].apply(solver.extract_answer)

unit_df['is_correct'] = unit_df['computed_answer'].astype(str).str.strip() == unit_df['answer'].astype(str).str.strip()

accuracy = unit_df['is_correct'].mean()
print(f"Accuracy by '{unit_df['label'].iloc[0]}': {accuracy * 100:.2f}%")

Accuracy by 'unit conversion': 90.72%

In [71]:

errors_df = unit_df[~unit_df['is_correct']]
for idx, row in errors_df.sample(3).iterrows():
    print(f"=== ID: {row['id']} ===")
    print(f"answer:  '{row['answer']}'")
    print(f"Computed:'{row['computed_answer']}'")
    print(f"Prompt: {row['prompt'][-80:]}\n")

=== ID: c7e03ea1 ===
answer:  '18.55'
Computed:'18.56'
Prompt: omes 29.97
30.02 m becomes 24.44
Now, convert the following measurement: 22.79 m

=== ID: 6dee6c75 ===
answer:  '52.91'
Computed:'52.90'
Prompt: omes 33.18
29.06 m becomes 37.98
Now, convert the following measurement: 40.48 m

=== ID: 82d14e7a ===
answer:  '45.53'
Computed:'45.52'
Prompt: comes 38.60
30.01 m becomes 27.49
Now, convert the following measurement: 49.7 m

### gravitational

In [72]:
grav_df = data[data['label'] == 'gravitational'].copy()

solver = GravitationalSolver()

grav_df['generated_cot'] = grav_df['prompt'].apply(solver.generate_cot)

grav_df['computed_answer'] = grav_df['generated_cot'].apply(solver.extract_answer)

grav_df['is_correct'] = grav_df['computed_answer'].astype(str).str.strip() == grav_df['answer'].astype(str).str.strip()

accuracy = grav_df['is_correct'].mean()
print(f"Accuracy by '{grav_df['label'].iloc[0]}': {accuracy * 100:.2f}%")

Accuracy by 'gravitational': 77.46%

In [73]:

errors_df = grav_df[~grav_df['is_correct']]
for idx, row in errors_df.sample(3).iterrows():
    print(f"=== ID: {row['id']} ===")
    print(f"answer:  '{row['answer']}'")
    print(f"Computed:'{row['computed_answer']}'")
    print(f"Prompt: {row['prompt'][-80:]}\n")

=== ID: 479e86b4 ===
answer:  '20.1'
Computed:'20.10'
Prompt: = 52.77 m
Now, determine the falling distance for t = 2.16s given d = 0.5*g*t^2.

=== ID: a4f165c1 ===
answer:  '61.38'
Computed:'61.35'
Prompt:  = 6.51 m
Now, determine the falling distance for t = 3.53s given d = 0.5*g*t^2.

=== ID: d7032308 ===
answer:  '186.4'
Computed:'186.40'
Prompt:  183.01 m
Now, determine the falling distance for t = 4.38s given d = 0.5*g*t^2.

### encryption

In [74]:
enc_df = data[data['label'] == 'encryption'].copy()

global_vocab = set()
for prompt in enc_df['prompt']:
    lines = [l.strip() for l in prompt.lower().splitlines() if "->" in l]
    for line in lines:
        plain = line.split("->", 1)[1]
        words = re.sub(r"[^a-z\s]", "", plain).split()
        global_vocab.update(words)

#for ans in enc_df['answer']:
#    if isinstance(ans, str):
#         global_vocab.update(re.sub(r"[^a-z\s]", "", ans.lower()).split())

print(f"Vocabulary from prompts: {len(global_vocab)}\n")

solver = EncryptionSolver(vocabulary=global_vocab)

enc_df['generated_cot'] = enc_df['prompt'].apply(lambda x: solver.generate_cot(x))
enc_df['computed_answer'] = enc_df['generated_cot'].apply(solver.extract_answer)

failed_mask = enc_df['computed_answer'].isna()
print(f"Fail on first run: {failed_mask.sum()} rows {len(enc_df)}\n")

if failed_mask.sum() > 0:
    def solve_with_fallback(row):
        return solver.generate_cot(row['prompt'], answer_hint=row['answer'])

    enc_df.loc[failed_mask, 'generated_cot'] = enc_df[failed_mask].apply(solve_with_fallback, axis=1)
    
    enc_df.loc[failed_mask, 'computed_answer'] = enc_df.loc[failed_mask, 'generated_cot'].apply(solver.extract_answer)

enc_df['is_correct'] = enc_df['computed_answer'] == enc_df['answer'].astype(str).str.lower().str.strip()
final_accuracy = enc_df['is_correct'].mean() * 100

print(f"Final Accuracy: {final_accuracy:.2f}%")

Vocabulary from prompts: 77

Fail on first run: 0 rows 1576

Final Accuracy: 99.05%

###

In [75]:
from pandarallel import pandarallel

pandarallel.initialize(nb_workers=24, progress_bar=True)

INFO: Pandarallel will run on 24 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [76]:
eq_df = data[data['label'] == 'equations transformation'].copy()

In [77]:
solver = EnsembleEquationsSolver()

eq_df['generated_cot'] = eq_df['prompt'].parallel_apply(solver.generate_cot)
eq_df['computed_answer'] = eq_df['generated_cot'].parallel_apply(solver.extract_answer)

# Если answer является строкой (символы или числа)
eq_df['is_correct'] = eq_df['computed_answer'] == eq_df['answer'].astype(str).str.strip()

accuracy = eq_df['is_correct'].mean()
print(f"Accuracy (Unified Solver): {accuracy * 100:.2f}%")

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=65), Label(value='0 / 65'))), HBox…

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=65), Label(value='0 / 65'))), HBox…

Accuracy (Unified Solver): 40.19%

In [78]:
# Фильтруем строки с ошибками (nan) и смотрим, на чем именно падает алгоритм
errors = eq_df[eq_df['computed_answer'] == 'nan']
if not errors.empty:
    print("\n--- ПРИМЕРЫ ОШИБОК ПАРСИНГА ИЛИ ГЕНЕРАЦИИ ---")
    print(errors[['prompt', 'generated_cot']].head(20).to_string())

# Если алгоритм выдает ответ, но он не совпадает с таргетом:
wrong_answers = eq_df[(eq_df['computed_answer'] != 'nan') & (~eq_df['is_correct'])]
if not wrong_answers.empty:
    print("\n--- ПРИМЕРЫ НЕВЕРНЫХ РЕШЕНИЙ ---")
    print(wrong_answers[['prompt', 'computed_answer', 'answer']].sample(20).to_string())

--- ПРИМЕРЫ НЕВЕРНЫХ РЕШЕНИЙ ---
                                                                                                                                                                                                                       prompt computed_answer answer
3368  In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n{{-(( = &&\n((-## = -{{\n[@+|& = [@|&\n|)*[{ = /&"[\n[#+#" = [##"\nNow, determine the result for: {@*|{            {@|{   /(#)
8185      In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n]]-|' = "%\n]"-%] = "\n$"*?$ = "|@`\n'|*#` = ##$\n'?+]% = |||\nNow, determine the result for: ?`*]%            ?`]%   %"|@
5696                           In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n'{*\$ = |"||\n||*:" = |){:\n"|*$> = ^$':\nNow, determine the result for: |'+$'            |'$'    >\:
1783                In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n$>:$' = [$\n@\/|> = '`$#\n$#/@` = @[`$\n'`:[% = '$:\nNow, determine the result for: '|(`$            `$'|    #$$
625     In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n<\|[$ = $:[\n\)#$' = <[<\n{'#{` = <'`\n{)#`) = $<{[\n$\]@@ = )<\nNow, determine the result for: ['|<)            <)['    $$`
4988       In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n#`*>' = |>>#\n|'-:% = %>\n$"->$ = `\n!%+"% = %"\n:!+!> = !$%\nNow, determine the result for: >'-:"            :">'     #$
5501                                 In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n36)32 = 4\n33{82 = 2705\n79)80 = 1\nNow, determine the result for: 83)40              43      3
9086                               In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n}`|{] = ]@)\n[)|@] = @{\n)'#)] = #[@\nNow, determine the result for: ()"%}            %}()   (`))
5336                   In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n&'})( = %(\n^@}%> = @(\n>&|{) = (&'%\n{^})@ = ""\nNow, determine the result for: ()|)'            )'()   &("&
8932    In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n%](]< = (\\n%@{][ = )%@@\n]<!%) = [[\\n%%()% = ><\n@'{)] = )\@>\nNow, determine the result for: ">!'%            '%">    [%"
8547                             In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n^)*{! = :)>%\n)|->) = ^{\n>>*#{ = ##^^\nNow, determine the result for: >)-|)            |)>)     '%
710                  In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n#'%#> = ]\&]\n{[*(# = >\n]#%{@ = {#\#\n''/'] = ][\\nNow, determine the result for: #'%@]            @]#'   ]@>[
6336                    In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n!:[$? = ::?\n&$[:} = %!\n}}#:: = %%\n%{#`} = :`\nNow, determine the result for: '!>{?            {?'!   :'%?
210   In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n%$<`# = <]]\n%"/(] = #`]$\n`$<(( = <(]\n%"<\& = <$$\n#&/]( = ###"\nNow, determine the result for: "&/($            ($"&    %%\
7891                               In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n%?*$" = )$\n?)*?) = }"\n$)+<% = }%!}\nNow, determine the result for: !?+!$            !?!$    !!$
3750                              In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n84-33 = 51\n67*35 = 8204\n02*81 = 063\nNow, determine the result for: 34+88             131    031
6030          In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n[|+<$ = [&\n<#-'# = '\n<&-<$ = <\n&|+&` = <@\n[`+<] = [#$\nNow, determine the result for: <&+<#            <&<#     <'
4792                              In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n"{+{% = @@"\n%"-@" = -&(\n@)*)< = {{#\nNow, determine the result for: {(+)#            {()#    @&#
3080       In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n[&+/` = '!\n<\-<\ = \\n`|-'' = -<|\n/&*?\ = &/|\n//-?? = -``\nNow, determine the result for: &&+&`            &&&`     '!
8407                                In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n]]<&} = <(\n]}#]" = '&!\n'^#$! = $&\nNow, determine the result for: ')<')            ')')      '

In [79]:
errors_df = eq_df[~eq_df['is_correct']]
for idx, row in errors_df.sample(10).iterrows():
    print(f"=== ID: {row['id']} ===")
    print(f"answer:  '{row['answer']}'")
    print(f"Computed:'{row['computed_answer']}'")
    print(f"Prompt: {row['prompt'][-110:]}\n")

=== ID: 680b66f2 ===
answer:  '}$'
Computed:'!<<\'
Prompt: equations. Below are a few examples:
<{*^& = ^&<{
^|-[$ = ^<
[}*|< = |<[}
Now, determine the result for: !<+<\

=== ID: 58fed63a ===
answer:  '5'
Computed:'-82'
Prompt: to equations. Below are a few examples:
68*91 = 9168
06-65 = 4
86-72 = 41
Now, determine the result for: 11-39

=== ID: 5144897d ===
answer:  '0'
Computed:'1'
Prompt: . Below are a few examples:
99-66 = 6533
13:92 = 1
49|31 = 80
76|65 = 141
Now, determine the result for: 90:15

=== ID: 0bb591e6 ===
answer:  '%?<'
Computed:'"$%%'
Prompt: ions. Below are a few examples:
)(-)( = "
&(-(( = <
$(-(% = )<
<%-%$ = ??
Now, determine the result for: "$+%%

=== ID: 9935aa11 ===
answer:  '-`#'
Computed:')<<`'
Prompt: quations. Below are a few examples:
?@*?\ = ?\?@
(#*>< = ><(#
`\+)( = \##
Now, determine the result for: <`-)<

=== ID: cca882b8 ===
answer:  '>)<|'
Computed:'>)!{'
Prompt:  equations. Below are a few examples:
>{`!{ = >{!#
{|$|| = '<!
[&${& = <'
Now, determine the result for: !{`>)

=== ID: 180ddd62 ===
answer:  ']/'
Computed:'[)|)'
Prompt: few examples:
)"'&" = >""<
{"]>< = `<
``*&) = |&<
|<'{< = {|<
&<]`" = ]>>
Now, determine the result for: |)][)

=== ID: d407570e ===
answer:  ')}}&'
Computed:'(^#&'
Prompt:  Below are a few examples:
}|+#| = |%|
()+|( = |||
!|+|% = '%
#|+^' = ||'
Now, determine the result for: (^*#&

=== ID: d73ef5bf ===
answer:  '\(|'
Computed:']//$'
Prompt: ew examples:
](%?\ = \|$
)?%|/ = \$/
'':'/ = ]/(^
^|:'^ = /'|^
'^*\\ = ]/
Now, determine the result for: /$%]/

=== ID: bcb0993a ===
answer:  '!!!'
Computed:'"`[('
Prompt: equations. Below are a few examples:
{(-{" = :(!
||'[{ = [(\(
|\+{` = +"[
Now, determine the result for: [(-"`

In [87]:
eq_df[eq_df.is_correct].generated_cot.to_list()

["The examples provided do not behave like mathematical equations. The operator is acting as a string manipulation function.\nBy tracking how the characters move from the left side of the equation to the right side, we can determine the exact operation.\nThe consistent pattern across all examples is to concatenate the two strings together from left to right.\n\nNow, let's process the target strings '\\(' and '[#' using this exact logic.\n- Following the rule, the new sequence of characters becomes '\\([#'.\n\nFinal answer: \\([#",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we multiply the numbers.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 85 / 77.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 6644",
 "The examples provided do not behave like mathematical equations. The operator is acting as a string manipulation function.\nBy tracking how the characters move from the left side of the equation to the right side, we can determine the exact operation.\nThe consistent pattern across all examples is to concatenate the two strings together from left to right.\n\nNow, let's process the target strings '#>' and ']#' using this exact logic.\n- Following the rule, the new sequence of characters becomes '#>]#'.\n\nFinal answer: #>]#",
 "The examples provided do not behave like mathematical equations. The operator is acting as a string manipulation function.\nBy tracking how the characters move from the left side of the equation to the right side, we can determine the exact operation.\nThe consistent pattern across all examples is to concatenate the two strings together from left to right.\n\nNow, let's process the target strings '>$' and '$>' using this exact logic.\n- Following the rule, the new sequence of characters becomes '>$$>'.\n\nFinal answer: >$$>",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we subtract the second number from the first.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 81 ` 20.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 61",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we multiply the numbers.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 59 $ 49.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 2891",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we concatenate the numbers together.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 25 $ 96.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 2596",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we multiply the numbers and then subtract 1.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 20 - 75.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 1499",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we find the negative absolute difference between the numbers.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 54 - 89.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: -35",
 "The examples provided do not behave like mathematical equations. The operator is acting as a string manipulation function.\nBy tracking how the characters move from the left side of the equation to the right side, we can determine the exact operation.\nThe consistent pattern across all examples is to concatenate the second string first, followed by the first string.\n\nNow, let's process the target strings ':\\' and '&/' using this exact logic.\n- Following the rule, the new sequence of characters becomes '&/:\\'.\n\nFinal answer: &/:\\",
 'The provided examples do not form a consistent algebraic or string-based pattern.\nHowever, the target query consists of pure numbers and a standard operator `-`.\nIn the absence of a reliable hidden rule, the most logical approach is to trust standard base-10 mathematics.\nEvaluating 22 - 84 standardly.\n\nFinal answer: -62',
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we add the two numbers and then add 1.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 57 + 82.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 401",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we add the two numbers.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 65 + 23.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 88",
 "The examples provided do not behave like mathematical equations. The operator is acting as a string manipulation function.\nBy tracking how the characters move from the left side of the equation to the right side, we can determine the exact operation.\nThe consistent pattern across all examples is to concatenate the second string first, followed by the first string.\n\nNow, let's process the target strings '>>' and '|>' using this exact logic.\n- Following the rule, the new sequence of characters becomes '|>>>'.\n\nFinal answer: |>>>",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we add the two numbers and then add 1.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 90 ' 91.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 182",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we subtract the second number from the first.\nStep 3: Finally, we take the absolute value, removing any negative signs.\n\nNow, let's apply this exact sequence to the target query: 80 : 32.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 48",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we concatenate the numbers together.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 98 ^ 14.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 9814",
 "The unusual symbols and results in the examples suggest a cryptarithm or a substitution cipher where each character maps to a specific decimal digit.\nBy analyzing the mathematical relationships, we can deduce a valid 1-to-1 mapping and determine that the operator `]` actually performs standard `+`.\n\nLet's apply this logic to the target operands.\nFirst, we translate the target strings into their true base-10 values, apply the operation, and then encrypt the result back into characters using the derived mapping.\n\nFinal answer: }}^",
 "The examples provided do not behave like mathematical equations. The operator is acting as a string manipulation function.\nBy tracking how the characters move from the left side of the equation to the right side, we can determine the exact operation.\nThe consistent pattern across all examples is to concatenate the two strings together from left to right.\n\nNow, let's process the target strings ':(' and '|#' using this exact logic.\n- Following the rule, the new sequence of characters becomes ':(|#'.\n\nFinal answer: :(|#",
 'The provided examples do not form any consistent mathematical, digit-wise, or string manipulation pattern.\nSince no reliable rule can be extracted, we fall back to a basic heuristic combination.\nWe will simply concatenate the two target strings.\n\nFinal answer: (\\#%',
 "The examples provided do not behave like mathematical equations. The operator is acting as a string manipulation function.\nBy tracking how the characters move from the left side of the equation to the right side, we can determine the exact operation.\nThe consistent pattern across all examples is to concatenate the two strings together from left to right.\n\nNow, let's process the target strings ')@' and '\\{' using this exact logic.\n- Following the rule, the new sequence of characters becomes ')@\\{'.\n\nFinal answer: )@\\{",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we multiply the numbers and then add 1.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 25 } 95.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 2376",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we multiply the numbers and then add 1.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 54 ] 85.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 1162",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we subtract the second number from the first.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 59 - 81.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 77",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we subtract the second number from the first.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 52 - 99.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: -47",
 'First, let\'s analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we multiply the numbers.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let\'s apply this exact sequence to the target query: 02 " 68.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 0271',
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we add the two numbers and then subtract 1.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 32 ^ 10.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 41",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we add the two numbers.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 48 > 83.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 221",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we subtract the second number from the first.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 66 { 56.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 10",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we subtract the second number from the first.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 50 } 49.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 1",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we add the two numbers.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 98 $ 07.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 951",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must take the numbers exactly as they are provided.\nStep 2: Next, we add the two numbers.\nStep 3: Finally, we leave the result exactly as computed.\n\nNow, let's apply this exact sequence to the target query: 26 ' 35.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: 61",
 "First, let's analyze the underlying pattern in the provided examples.\nThe standard mathematical operators are being used as placeholders for a hidden, multi-step rule.\nBy observing the relationship between the inputs and outputs, the consistent sequence of operations is:\nStep 1: We must reverse the digits of each number.\nStep 2: Next, we subtract the second number from the first.\nStep 3: Finally, we reverse the digits of the final computed result.\n\nNow, let's apply this exact sequence to the target query: 61 - 47.\n- Working through the steps on the base operands generates the final formatted output.\n\nFinal answer: -85",

In [80]:
d = eq_df.sample(3)

In [81]:
d.prompt.to_list()

["In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n06-45 = 6\n49*58 = 1997\n22*17 = 3651\n42-65 = -23\n69*08 = 1867\nNow, determine the result for: 24*88",
 "In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n65+83 = 8365\n62-23 = -6\n69*72 = 2952\nNow, determine the result for: 72+44",
 "In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n&%+@] = `?&\n@>*<@ = &>?<\n@`*`% = `^&%\nNow, determine the result for: `]*@>"]

In [82]:
d.answer

2389    7963
3944    4472
6491     <<<
Name: answer, dtype: str

### bit manipulation

In [83]:
bit_df = data[data['label'] == 'bit manipulation'].copy()
solver = BitManipulationSolver()

bit_df['generated_cot'] = bit_df['prompt'].apply(solver.generate_cot)
bit_df['computed_answer'] = bit_df['generated_cot'].apply(solver.extract_answer)
bit_df['is_correct'] = bit_df['computed_answer'].astype(str).str.strip() == bit_df['answer'].astype(str).str.strip()

accuracy = bit_df['is_correct'].mean()
print(f"Accuracy by 'bit manipulation': {accuracy * 100:.2f}%")

Accuracy by 'bit manipulation': 82.96%

In [84]:
errors_df = bit_df[~bit_df['is_correct']]
for idx, row in errors_df.sample(25).iterrows():
    print(f"=== ID: {row['id']} ===")
    print(f"answer:  '{row['answer']}'")
    print(f"Computed:'{row['computed_answer']}'")
    print(f"Prompt: {row['prompt'][-80:]}\n")

=== ID: 7dba5d8b ===
answer:  '11011111'
Computed:'11101111'
Prompt: 001111 -> 11110111
10010111 -> 11101011

Now, determine the output for: 11111010

=== ID: b275443b ===
answer:  '00111000'
Computed:'00111101'
Prompt: 101111 -> 00010111
00011100 -> 10110111

Now, determine the output for: 10100001

=== ID: eb12e80d ===
answer:  '11000111'
Computed:'11010011'
Prompt: 011001 -> 00110001
01110000 -> 11101110

Now, determine the output for: 11101101

=== ID: b265a4af ===
answer:  '00100100'
Computed:'00101100'
Prompt: 011111 -> 00000010
01010110 -> 10100100

Now, determine the output for: 00110110

=== ID: 004ef7c7 ===
answer:  '11111111'
Computed:'11110111'
Prompt: 000010 -> 11111010
00001010 -> 10111011

Now, determine the output for: 01010101

=== ID: 7192535b ===
answer:  '00000010'
Computed:'00001010'
Prompt: 001010 -> 00000100
11000110 -> 10001100

Now, determine the output for: 00100101

=== ID: ada01a20 ===
answer:  '10000000'
Computed:'10000010'
Prompt: 010010 -> 01001010
10111011 -> 00000011

Now, determine the output for: 00100110

=== ID: 2ce41663 ===
answer:  '01100011'
Computed:'01111111'
Prompt: 011100 -> 00100111
00001110 -> 11011011

Now, determine the output for: 11001101

=== ID: 021ed764 ===
answer:  '11111101'
Computed:'11110101'
Prompt: 000100 -> 11111110
01110010 -> 11111111

Now, determine the output for: 10000100

=== ID: 8d90150c ===
answer:  '10101000'
Computed:'10101010'
Prompt: 100010 -> 00010001
00101000 -> 01000000

Now, determine the output for: 00110101

=== ID: 52d72862 ===
answer:  '01001000'
Computed:'01000000'
Prompt: 111100 -> 11110111
00000010 -> 00000100

Now, determine the output for: 00100110

=== ID: b82b2a02 ===
answer:  '01000110'
Computed:'01000010'
Prompt: 010110 -> 01001010
01101010 -> 10100101

Now, determine the output for: 01010011

=== ID: d155a508 ===
answer:  '01010110'
Computed:'01010111'
Prompt: 110111 -> 11101111
11000100 -> 11101111

Now, determine the output for: 11001001

=== ID: 0ec17d2e ===
answer:  '00111111'
Computed:'01011111'
Prompt: 000101 -> 10111010
11001000 -> 01111100

Now, determine the output for: 10011111

=== ID: 177b7d80 ===
answer:  '10011111'
Computed:'10111111'
Prompt: 010000 -> 01111111
10100100 -> 01111011

Now, determine the output for: 01111100

=== ID: bb056bc9 ===
answer:  '11010101'
Computed:'11001101'
Prompt: 100111 -> 01011001
00011100 -> 01101111

Now, determine the output for: 01000110

=== ID: 1d930d32 ===
answer:  '00000100'
Computed:'00000010'
Prompt: 111101 -> 11110101
10001100 -> 00010000

Now, determine the output for: 10000110

=== ID: a62dd199 ===
answer:  '10111011'
Computed:'00111011'
Prompt: 000001 -> 01110101
11010001 -> 11110101

Now, determine the output for: 11001010

=== ID: 4fb6838e ===
answer:  '10000101'
Computed:'01000101'
Prompt: 011011 -> 10000010
01001100 -> 00000010

Now, determine the output for: 10101011

=== ID: 288c7eca ===
answer:  '01111111'
Computed:'10111111'
Prompt: 111111 -> 10111111
00101101 -> 00111111

Now, determine the output for: 10110101

=== ID: 6a41d37b ===
answer:  '00101011'
Computed:'00101111'
Prompt: 011101 -> 10000110
01100010 -> 10011001

Now, determine the output for: 01011011

=== ID: fa6f754d ===
answer:  '11000000'
Computed:'01011000'
Prompt: 100100 -> 01001010
10111001 -> 01011011

Now, determine the output for: 10001111

=== ID: b8aa3072 ===
answer:  '00000011'
Computed:'00000111'
Prompt: 100010 -> 01011001
00111010 -> 00010101

Now, determine the output for: 00101111

=== ID: eb20ea88 ===
answer:  '00110000'
Computed:'01110000'
Prompt: 101000 -> 10001010
00110010 -> 00101111

Now, determine the output for: 00000011

=== ID: fbdf7656 ===
answer:  '10100100'
Computed:'10100000'
Prompt: 101101 -> 01010110
10101011 -> 00010110

Now, determine the output for: 11001010